<?php

use Illuminate\Database\Seeder;

class OtherTablesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     * ONLY FOR ONLY READ TABLES
     *
     * @return void
     */
    public function run()
    {
        // Table banks
        \DB::table('banks')->insert(array('name' => 'COMMONWEALTH BANK OF AUSTRALIA (CBA)'));
        \DB::table('banks')->insert(array('name' => 'WESTPAC BANKING CORPORATION (WESTPAC)'));
        \DB::table('banks')->insert(array('name' => 'NATIONAL AUSTRALIA BANK (NAB)'));
        \DB::table('banks')->insert(array('name' => 'AUSTRALIA AND NEW ZEALAND BANKING GROUP (ANZ)'));

        // Table client_types
        \DB::table('client_types')->insert(array('name' => 'SPRING CLEANING'));
        \DB::table('client_types')->insert(array('name' => 'MOVE IN CLEANING'));
        \DB::table('client_types')->insert(array('name' => 'MOVE OUT CLEANING'));
        \DB::table('client_types')->insert(array('name' => 'END OF LEASE'));
        \DB::table('client_types')->insert(array('name' => 'BUILDERS CLEANING'));
        \DB::table('client_types')->insert(array('name' => 'REGULAR DOMESTIC CLEANING'));

        // Table documents
        \DB::table('documents')->insert(array('name' => 'DNI'));
        \DB::table('documents')->insert(array('name' => 'PASSPORT'));
        \DB::table('documents')->insert(array('name' => 'DRIVING LICENCE'));

        // Table english_levels
        \DB::table('english_levels')->insert(array('lse_class' => 'BEGINNER', 'description' => 'I DO NOT SPEAK ANY ENGLISH.', 'cef' => '0'));
        \DB::table('english_levels')->insert(array('lse_class' => 'ELEMENTARY', 'description' => 'I CAN SAY AND UNDERSTAND A FEW THINGS IN ENGLISH.', 'cef' => 'A1/2'));
        \DB::table('english_levels')->insert(array('lse_class' => 'PRE-INTERMEDIATE', 'description' => 'I CAN COMMUNICATE SIMPLY AND UNDERSTAND IN FAMILIAR SITUATIONS BUT ONLY WITH SOME DIFFICULTY.', 'cef' => 'A2'));
        \DB::table('english_levels')->insert(array('lse_class' => 'LOW INTERMEDIATE', 'description' => 'I CAN MAKE SIMPLE SENTENCES AND CAN UNDERSTAND THE MAIN POINTS OF A CONVERSATION BUT NEED MUCH MORE VOCABULARY.', 'cef' => 'B1'));
        \DB::table('english_levels')->insert(array('lse_class' => 'INTERMEDIATE', 'description' => 'I CAN SPEAK AND UNDERSTAND REASONABLY WELL AND CAN USE BASIC TENSES BUT HAVE PROBLEMS WITH MORE COMPLEX GRAMMAR AND VOCABULARY.', 'cef' => 'B1'));
        \DB::table('english_levels')->insert(array('lse_class' => 'UPPER INTERMEDIATE', 'description' => 'I SPEAK AND UNDERSTAND WELL BUT STILL MAKE MISTAKES AND FAIL TO MAKE MYSELF UNDERSTOOD OCCASIONALLY.', 'cef' => 'B2'));
        \DB::table('english_levels')->insert(array('lse_class' => 'PRE-ADVANCED', 'description' => 'I SPEAK AND UNDERSTAND WELL BUT STILL MAKE MISTAKES AND FAIL TO MAKE MYSELF UNDERSTOOD OCCASIONALLY.', 'cef' => 'C1'));
        \DB::table('english_levels')->insert(array('lse_class' => 'ADVANCED', 'description' => 'I SPEAK AND UNDERSTAND VERY WELL BUT SOMETIMES HAVE PROBLEMS WITH UNFAMILIAR SITUATIONS AND VOCABULARY.', 'cef' => 'C2'));
        \DB::table('english_levels')->insert(array('lse_class' => 'VERY ADVANCED', 'description' => 'I SPEAK AND UNDERSTAND ENGLISH COMPLETELY FLUENTLY.', 'cef' => 'C2'));
        \DB::table('english_levels')->insert(array('lse_class' => 'NATIVE', 'description' => 'I AM A NATIVE SPEAKER', 'cef' => 'N'));

        // Table languages
        \DB::table('languages')->insert(array('code' => 'AB', 'name' => 'ABKHAZ'));
        \DB::table('languages')->insert(array('code' => 'AA', 'name' => 'AFAR'));
        \DB::table('languages')->insert(array('code' => 'AF', 'name' => 'AFRIKAANS'));
        \DB::table('languages')->insert(array('code' => 'AK', 'name' => 'AKAN'));
        \DB::table('languages')->insert(array('code' => 'SQ', 'name' => 'ALBANIAN'));
        \DB::table('languages')->insert(array('code' => 'AM', 'name' => 'AMHARIC'));
        \DB::table('languages')->insert(array('code' => 'AR', 'name' => 'ARABIC'));
        \DB::table('languages')->insert(array('code' => 'AN', 'name' => 'ARAGONESE'));
        \DB::table('languages')->insert(array('code' => 'HY', 'name' => 'ARMENIAN'));
        \DB::table('languages')->insert(array('code' => 'AS', 'name' => 'ASSAMESE'));
        \DB::table('languages')->insert(array('code' => 'AV', 'name' => 'AVARIC'));
        \DB::table('languages')->insert(array('code' => 'AE', 'name' => 'AVESTAN'));
        \DB::table('languages')->insert(array('code' => 'AY', 'name' => 'AYMARA'));
        \DB::table('languages')->insert(array('code' => 'AZ', 'name' => 'AZERBAIJANI'));
        \DB::table('languages')->insert(array('code' => 'BM', 'name' => 'BAMBARA'));
        \DB::table('languages')->insert(array('code' => 'BA', 'name' => 'BASHKIR'));
        \DB::table('languages')->insert(array('code' => 'EU', 'name' => 'BASQUE'));
        \DB::table('languages')->insert(array('code' => 'BE', 'name' => 'BELARUSIAN'));
        \DB::table('languages')->insert(array('code' => 'BN', 'name' => 'BENGALI'));
        \DB::table('languages')->insert(array('code' => 'BH', 'name' => 'BIHARI'));
        \DB::table('languages')->insert(array('code' => 'BI', 'name' => 'BISLAMA'));
        \DB::table('languages')->insert(array('code' => 'BS', 'name' => 'BOSNIAN'));
        \DB::table('languages')->insert(array('code' => 'BR', 'name' => 'BRETON'));
        \DB::table('languages')->insert(array('code' => 'BG', 'name' => 'BULGARIAN'));
        \DB::table('languages')->insert(array('code' => 'MY', 'name' => 'BURMESE'));
        \DB::table('languages')->insert(array('code' => 'CA', 'name' => 'CATALAN; VALENCIAN'));
        \DB::table('languages')->insert(array('code' => 'CH', 'name' => 'CHAMORRO'));
        \DB::table('languages')->insert(array('code' => 'CE', 'name' => 'CHECHEN'));
        \DB::table('languages')->insert(array('code' => 'NY', 'name' => 'CHICHEWA; CHEWA; NYANJA'));
        \DB::table('languages')->insert(array('code' => 'ZH', 'name' => 'CHINESE'));
        \DB::table('languages')->insert(array('code' => 'CV', 'name' => 'CHUVASH'));
        \DB::table('languages')->insert(array('code' => 'KW', 'name' => 'CORNISH'));
        \DB::table('languages')->insert(array('code' => 'CO', 'name' => 'CORSICAN'));
        \DB::table('languages')->insert(array('code' => 'CR', 'name' => 'CREE'));
        \DB::table('languages')->insert(array('code' => 'HR', 'name' => 'CROATIAN'));
        \DB::table('languages')->insert(array('code' => 'CS', 'name' => 'CZECH'));
        \DB::table('languages')->insert(array('code' => 'DA', 'name' => 'DANISH'));
        \DB::table('languages')->insert(array('code' => 'DV', 'name' => 'DIVEHI; DHIVEHI; MALDIVIAN;'));
        \DB::table('languages')->insert(array('code' => 'NL', 'name' => 'DUTCH'));
        \DB::table('languages')->insert(array('code' => 'EN', 'name' => 'ENGLISH'));
        \DB::table('languages')->insert(array('code' => 'EO', 'name' => 'ESPERANTO'));
        \DB::table('languages')->insert(array('code' => 'ET', 'name' => 'ESTONIAN'));
        \DB::table('languages')->insert(array('code' => 'EE', 'name' => 'EWE'));
        \DB::table('languages')->insert(array('code' => 'FO', 'name' => 'FAROESE'));
        \DB::table('languages')->insert(array('code' => 'FJ', 'name' => 'FIJIAN'));
        \DB::table('languages')->insert(array('code' => 'FI', 'name' => 'FINNISH'));
        \DB::table('languages')->insert(array('code' => 'FR', 'name' => 'FRENCH'));
        \DB::table('languages')->insert(array('code' => 'FF', 'name' => 'FULA; FULAH; PULAAR; PULAR'));
        \DB::table('languages')->insert(array('code' => 'GL', 'name' => 'GALICIAN'));
        \DB::table('languages')->insert(array('code' => 'KA', 'name' => 'GEORGIAN'));
        \DB::table('languages')->insert(array('code' => 'DE', 'name' => 'GERMAN'));
        \DB::table('languages')->insert(array('code' => 'EL', 'name' => 'GREEK (MODERN)'));
        \DB::table('languages')->insert(array('code' => 'GN', 'name' => 'GUARANÍ'));
        \DB::table('languages')->insert(array('code' => 'GU', 'name' => 'GUJARATI'));
        \DB::table('languages')->insert(array('code' => 'HT', 'name' => 'HAITIAN; HAITIAN CREOLE'));
        \DB::table('languages')->insert(array('code' => 'HA', 'name' => 'HAUSA'));
        \DB::table('languages')->insert(array('code' => 'HE', 'name' => 'HEBREW (MODERN)'));
        \DB::table('languages')->insert(array('code' => 'HZ', 'name' => 'HERERO'));
        \DB::table('languages')->insert(array('code' => 'HI', 'name' => 'HINDI'));
        \DB::table('languages')->insert(array('code' => 'HO', 'name' => 'HIRI MOTU'));
        \DB::table('languages')->insert(array('code' => 'HU', 'name' => 'HUNGARIAN'));
        \DB::table('languages')->insert(array('code' => 'IA', 'name' => 'INTERLINGUA'));
        \DB::table('languages')->insert(array('code' => 'ID', 'name' => 'INDONESIAN'));
        \DB::table('languages')->insert(array('code' => 'IE', 'name' => 'INTERLINGUE'));
        \DB::table('languages')->insert(array('code' => 'GA', 'name' => 'IRISH'));
        \DB::table('languages')->insert(array('code' => 'IG', 'name' => 'IGBO'));
        \DB::table('languages')->insert(array('code' => 'IK', 'name' => 'INUPIAQ'));
        \DB::table('languages')->insert(array('code' => 'IO', 'name' => 'IDO'));
        \DB::table('languages')->insert(array('code' => 'IS', 'name' => 'ICELANDIC'));
        \DB::table('languages')->insert(array('code' => 'IT', 'name' => 'ITALIAN'));
        \DB::table('languages')->insert(array('code' => 'IU', 'name' => 'INUKTITUT'));
        \DB::table('languages')->insert(array('code' => 'JA', 'name' => 'JAPANESE'));
        \DB::table('languages')->insert(array('code' => 'JV', 'name' => 'JAVANESE'));
        \DB::table('languages')->insert(array('code' => 'KL', 'name' => 'KALAALLISUT; GREENLANDIC'));
        \DB::table('languages')->insert(array('code' => 'KN', 'name' => 'KANNADA'));
        \DB::table('languages')->insert(array('code' => 'KR', 'name' => 'KANURI'));
        \DB::table('languages')->insert(array('code' => 'KS', 'name' => 'KASHMIRI'));
        \DB::table('languages')->insert(array('code' => 'KK', 'name' => 'KAZAKH'));
        \DB::table('languages')->insert(array('code' => 'KM', 'name' => 'KHMER'));
        \DB::table('languages')->insert(array('code' => 'KI', 'name' => 'KIKUYU'));
        \DB::table('languages')->insert(array('code' => 'RW', 'name' => 'KINYARWANDA'));
        \DB::table('languages')->insert(array('code' => 'KY', 'name' => 'KIRGHIZ; KYRGYZ'));
        \DB::table('languages')->insert(array('code' => 'KV', 'name' => 'KOMI'));
        \DB::table('languages')->insert(array('code' => 'KG', 'name' => 'KONGO'));
        \DB::table('languages')->insert(array('code' => 'KO', 'name' => 'KOREAN'));
        \DB::table('languages')->insert(array('code' => 'KU', 'name' => 'KURDISH'));
        \DB::table('languages')->insert(array('code' => 'KJ', 'name' => 'KWANYAMA; KUANYAMA'));
        \DB::table('languages')->insert(array('code' => 'LA', 'name' => 'LATIN'));
        \DB::table('languages')->insert(array('code' => 'LB', 'name' => 'LUXEMBOURGISH; LETZEBURGESCH'));
        \DB::table('languages')->insert(array('code' => 'LG', 'name' => 'LUGANDA'));
        \DB::table('languages')->insert(array('code' => 'LI', 'name' => 'LIMBURGISH; LIMBURGAN; LIMBURGER'));
        \DB::table('languages')->insert(array('code' => 'LN', 'name' => 'LINGALA'));
        \DB::table('languages')->insert(array('code' => 'LO', 'name' => 'LAO'));
        \DB::table('languages')->insert(array('code' => 'LT', 'name' => 'LITHUANIAN'));
        \DB::table('languages')->insert(array('code' => 'LU', 'name' => 'LUBA-KATANGA'));
        \DB::table('languages')->insert(array('code' => 'LV', 'name' => 'LATVIAN'));
        \DB::table('languages')->insert(array('code' => 'GV', 'name' => 'MANX'));
        \DB::table('languages')->insert(array('code' => 'MK', 'name' => 'MACEDONIAN'));
        \DB::table('languages')->insert(array('code' => 'MG', 'name' => 'MALAGASY'));
        \DB::table('languages')->insert(array('code' => 'MS', 'name' => 'MALAY'));
        \DB::table('languages')->insert(array('code' => 'ML', 'name' => 'MALAYALAM'));
        \DB::table('languages')->insert(array('code' => 'MT', 'name' => 'MALTESE'));
        \DB::table('languages')->insert(array('code' => 'MI', 'name' => 'MAORI'));
        \DB::table('languages')->insert(array('code' => 'MR', 'name' => 'MARATHI (MARAHI)'));
        \DB::table('languages')->insert(array('code' => 'MH', 'name' => 'MARSHALLESE'));
        \DB::table('languages')->insert(array('code' => 'MN', 'name' => 'MONGOLIAN'));
        \DB::table('languages')->insert(array('code' => 'NA', 'name' => 'NAURU'));
        \DB::table('languages')->insert(array('code' => 'NV', 'name' => 'NAVAJO, NAVAHO'));
        \DB::table('languages')->insert(array('code' => 'NB', 'name' => 'NORWEGIAN BOKMÅL'));
        \DB::table('languages')->insert(array('code' => 'ND', 'name' => 'NORTH NDEBELE'));
        \DB::table('languages')->insert(array('code' => 'NE', 'name' => 'NEPALI'));
        \DB::table('languages')->insert(array('code' => 'NG', 'name' => 'NDONGA'));
        \DB::table('languages')->insert(array('code' => 'NN', 'name' => 'NORWEGIAN NYNORSK'));
        \DB::table('languages')->insert(array('code' => 'NO', 'name' => 'NORWEGIAN'));
        \DB::table('languages')->insert(array('code' => 'II', 'name' => 'NUOSU'));
        \DB::table('languages')->insert(array('code' => 'NR', 'name' => 'SOUTH NDEBELE'));
        \DB::table('languages')->insert(array('code' => 'OC', 'name' => 'OCCITAN'));
        \DB::table('languages')->insert(array('code' => 'OJ', 'name' => 'OJIBWE; OJIBWA'));
        \DB::table('languages')->insert(array('code' => 'CU', 'name' => 'OLD CHURCH SLAVONIC; CHURCH SLAVIC; CHURCH SLAVONIC; OLD BULGARIAN; OLD SLAVONIC' ));
        \DB::table('languages')->insert(array('code' => 'OM', 'name' => 'OROMO'));
        \DB::table('languages')->insert(array('code' => 'OR', 'name' => 'ORIYA'));
        \DB::table('languages')->insert(array('code' => 'OS', 'name' => 'OSSETIAN; OSSETIC'));
        \DB::table('languages')->insert(array('code' => 'PA', 'name' => 'PANJABI; PUNJABI'));
        \DB::table('languages')->insert(array('code' => 'PI', 'name' => 'PALI'));
        \DB::table('languages')->insert(array('code' => 'FA', 'name' => 'PERSIAN'));
        \DB::table('languages')->insert(array('code' => 'PL', 'name' => 'POLISH'));
        \DB::table('languages')->insert(array('code' => 'PS', 'name' => 'PASHTO; PUSHTO'));
        \DB::table('languages')->insert(array('code' => 'PT', 'name' => 'PORTUGUESE'));
        \DB::table('languages')->insert(array('code' => 'QU', 'name' => 'QUECHUA'));
        \DB::table('languages')->insert(array('code' => 'RM', 'name' => 'ROMANSH'));
        \DB::table('languages')->insert(array('code' => 'RN', 'name' => 'KIRUNDI'));
        \DB::table('languages')->insert(array('code' => 'RO', 'name' => 'ROMANIAN; MOLDAVIAN; MOLDOVAN'));
        \DB::table('languages')->insert(array('code' => 'RU', 'name' => 'RUSSIAN'));
        \DB::table('languages')->insert(array('code' => 'SA', 'name' => 'SANSKRIT (SASKTA)'));
        \DB::table('languages')->insert(array('code' => 'SC', 'name' => 'SARDINIAN'));
        \DB::table('languages')->insert(array('code' => 'SD', 'name' => 'SINDHI'));
        \DB::table('languages')->insert(array('code' => 'SE', 'name' => 'NORTHERN SAMI'));
        \DB::table('languages')->insert(array('code' => 'SM', 'name' => 'SAMOAN'));
        \DB::table('languages')->insert(array('code' => 'SG', 'name' => 'SANGO'));
        \DB::table('languages')->insert(array('code' => 'SR', 'name' => 'SERBIAN'));
        \DB::table('languages')->insert(array('code' => 'GD', 'name' => 'SCOTTISH GAELIC; GAELIC'));
        \DB::table('languages')->insert(array('code' => 'SN', 'name' => 'SHONA'));
        \DB::table('languages')->insert(array('code' => 'SI', 'name' => 'SINHALA; SINHALESE'));
        \DB::table('languages')->insert(array('code' => 'SK', 'name' => 'SLOVAK'));
        \DB::table('languages')->insert(array('code' => 'SL', 'name' => 'SLOVENE'));
        \DB::table('languages')->insert(array('code' => 'SO', 'name' => 'SOMALI'));
        \DB::table('languages')->insert(array('code' => 'ST', 'name' => 'SOUTHERN SOTHO'));
        \DB::table('languages')->insert(array('code' => 'ES', 'name' => 'SPANISH; CASTILIAN'));
        \DB::table('languages')->insert(array('code' => 'SU', 'name' => 'SUNDANESE'));
        \DB::table('languages')->insert(array('code' => 'SW', 'name' => 'SWAHILI'));
        \DB::table('languages')->insert(array('code' => 'SS', 'name' => 'SWATI'));
        \DB::table('languages')->insert(array('code' => 'SV', 'name' => 'SWEDISH'));
        \DB::table('languages')->insert(array('code' => 'TA', 'name' => 'TAMIL'));
        \DB::table('languages')->insert(array('code' => 'TE', 'name' => 'TELUGU'));
        \DB::table('languages')->insert(array('code' => 'TG', 'name' => 'TAJIK'));
        \DB::table('languages')->insert(array('code' => 'TH', 'name' => 'THAI'));
        \DB::table('languages')->insert(array('code' => 'TI', 'name' => 'TIGRINYA'));
        \DB::table('languages')->insert(array('code' => 'BO', 'name' => 'TIBETAN STANDARD; TIBETAN CENTRAL'));
        \DB::table('languages')->insert(array('code' => 'TK', 'name' => 'TURKMEN'));
        \DB::table('languages')->insert(array('code' => 'TL', 'name' => 'TAGALOG'));
        \DB::table('languages')->insert(array('code' => 'TN', 'name' => 'TSWANA'));
        \DB::table('languages')->insert(array('code' => 'TO', 'name' => 'TONGA (TONGA ISLANDS)'));
        \DB::table('languages')->insert(array('code' => 'TR', 'name' => 'TURKISH'));
        \DB::table('languages')->insert(array('code' => 'TS', 'name' => 'TSONGA'));
        \DB::table('languages')->insert(array('code' => 'TT', 'name' => 'TATAR'));
        \DB::table('languages')->insert(array('code' => 'TW', 'name' => 'TWI'));
        \DB::table('languages')->insert(array('code' => 'TY', 'name' => 'TAHITIAN'));
        \DB::table('languages')->insert(array('code' => 'UG', 'name' => 'UIGHUR; UYGHUR'));
        \DB::table('languages')->insert(array('code' => 'UK', 'name' => 'UKRAINIAN'));
        \DB::table('languages')->insert(array('code' => 'UR', 'name' => 'URDU'));
        \DB::table('languages')->insert(array('code' => 'UZ', 'name' => 'UZBEK'));
        \DB::table('languages')->insert(array('code' => 'VE', 'name' => 'VENDA'));
        \DB::table('languages')->insert(array('code' => 'VI', 'name' => 'VIETNAMESE'));
        \DB::table('languages')->insert(array('code' => 'VO', 'name' => 'VOLAPÜK'));
        \DB::table('languages')->insert(array('code' => 'WA', 'name' => 'WALLOON'));
        \DB::table('languages')->insert(array('code' => 'CY', 'name' => 'WELSH'));
        \DB::table('languages')->insert(array('code' => 'WO', 'name' => 'WOLOF'));
        \DB::table('languages')->insert(array('code' => 'FY', 'name' => 'WESTERN FRISIAN'));
        \DB::table('languages')->insert(array('code' => 'XH', 'name' => 'XHOSA'));
        \DB::table('languages')->insert(array('code' => 'YI', 'name' => 'YIDDISH'));
        \DB::table('languages')->insert(array('code' => 'YO', 'name' => 'YORUBA'));
        \DB::table('languages')->insert(array('code' => 'ZA', 'name' => 'ZHUANG; CHUANG'));

        // Table partcategorys
        \DB::table('part_categories')->insert(array('name' => 'KITCHEN'));
        \DB::table('part_categories')->insert(array('name' => 'BATHROOM'));
        \DB::table('part_categories')->insert(array('name' => 'WINDOWS / BLINDS - WASH & BLADE WIPE'));
        \DB::table('part_categories')->insert(array('name' => 'WALLS & DOORS'));
        \DB::table('part_categories')->insert(array('name' => 'VENTS & LIGHT FITTINGS'));
        \DB::table('part_categories')->insert(array('name' => 'FLOORS'));

        // Table parts
        \DB::table('parts')->insert(array('part_category_id' => '1', 'partid' => '1', 'name' => 'OVEN & RANGEHOOD'));
        \DB::table('parts')->insert(array('part_category_id' => '1', 'partid' => '2', 'name' => 'KITCHEN CUPBOARDS / DOORS / BENCHTOPS'));
        \DB::table('parts')->insert(array('part_category_id' => '1', 'partid' => '3', 'name' => 'PANTRY - LARGE CUPBOARD'));
        \DB::table('parts')->insert(array('part_category_id' => '1', 'partid' => '4', 'name' => 'SPLASHBACKS / TILES'));
        \DB::table('parts')->insert(array('part_category_id' => '2', 'partid' => '1', 'name' => 'SHOWER - INCLUDING EXHAUST FAN'));
        \DB::table('parts')->insert(array('part_category_id' => '2', 'partid' => '2', 'name' => 'SINK & VANITY CUPBOARD'));
        \DB::table('parts')->insert(array('part_category_id' => '2', 'partid' => '3', 'name' => 'BATHROOM MIRROR CABINET'));
        \DB::table('parts')->insert(array('part_category_id' => '2', 'partid' => '4', 'name' => 'TOILET - INCLUDING WALLS'));
        \DB::table('parts')->insert(array('part_category_id' => '2', 'partid' => '5', 'name' => 'BATHTUB'));
        \DB::table('parts')->insert(array('part_category_id' => '3', 'partid' => '1', 'name' => 'INSIDE'));
        \DB::table('parts')->insert(array('part_category_id' => '3', 'partid' => '2', 'name' => 'OUTSIDE'));
        \DB::table('parts')->insert(array('part_category_id' => '3', 'partid' => '3', 'name' => 'WINDOW SILLS & SLIDING TRACKS'));
        \DB::table('parts')->insert(array('part_category_id' => '3', 'partid' => '4', 'name' => 'VENETIAN BLINDS'));
        \DB::table('parts')->insert(array('part_category_id' => '4', 'partid' => '1', 'name' => 'DRY FLAT MOP DUSTING - EACH WALL'));
        \DB::table('parts')->insert(array('part_category_id' => '4', 'partid' => '2', 'name' => 'SPOT CLEAN - EACH WALL'));
        \DB::table('parts')->insert(array('part_category_id' => '4', 'partid' => '3', 'name' => 'WASH - EACH WALL'));
        \DB::table('parts')->insert(array('part_category_id' => '4', 'partid' => '4', 'name' => 'MOULD REMOVAL - EACH WALL'));
        \DB::table('parts')->insert(array('part_category_id' => '4', 'partid' => '5', 'name' => 'SKIRTING BOARDS - WHOLE HOUSE PER LEVEL'));
        \DB::table('parts')->insert(array('part_category_id' => '4', 'partid' => '6', 'name' => 'DOORS & DOOR HANDLES'));
        \DB::table('parts')->insert(array('part_category_id' => '4', 'partid' => '7', 'name' => 'COBWEBS - WHOLE HOUSE PER LEVEL'));
        \DB::table('parts')->insert(array('part_category_id' => '4', 'partid' => '8', 'name' => 'LIGHT SWITCHES'));
        \DB::table('parts')->insert(array('part_category_id' => '5', 'partid' => '1', 'name' => 'VENT - DUST & WET WIPE'));
        \DB::table('parts')->insert(array('part_category_id' => '5', 'partid' => '2', 'name' => 'LIGHT FITTING - REMOVE / WASH & REPLACE)'));
        \DB::table('parts')->insert(array('part_category_id' => '6', 'partid' => '1', 'name' => 'VACUUMING - PER LEVEL'));
        \DB::table('parts')->insert(array('part_category_id' => '6', 'partid' => '2', 'name' => 'MOPPING - PER LEVEL'));
        \DB::table('parts')->insert(array('part_category_id' => '6', 'partid' => '3', 'name' => 'BALCONY - SWEEP & MOP / WASH'));

        // Table quote_hours
        \DB::table('quote_hours')->insert(array('part_category_id' => '1', 'partid' => '1', 'size_id' => '1', 'duration' => '00:15:00', 'created_at' => '2016-03-27 00:00:00', 'updated_at' => '2016-03-27 00:00:00'));
        \DB::table('quote_hours')->insert(array('part_category_id' => '1', 'partid' => '1', 'size_id' => '2', 'duration' => '00:15:00', 'created_at' => '2016-03-27 00:00:00', 'updated_at' => '2016-03-27 00:00:00'));
        \DB::table('quote_hours')->insert(array('part_category_id' => '1', 'partid' => '1', 'size_id' => '3', 'duration' => '00:15:00', 'created_at' => '2016-03-27 00:00:00', 'updated_at' => '2016-03-27 00:00:00'));
        \DB::table('quote_hours')->insert(array('part_category_id' => '1', 'partid' => '2', 'size_id' => '1', 'duration' => '00:15:00', 'created_at' => '2016-03-27 00:00:00', 'updated_at' => '2016-03-27 00:00:00'));
        \DB::table('quote_hours')->insert(array('part_category_id' => '1', 'partid' => '2', 'size_id' => '2', 'duration' => '00:15:00', 'created_at' => '2016-03-27 00:00:00', 'updated_at' => '2016-03-27 00:00:00'));
        \DB::table('quote_hours')->insert(array('part_category_id' => '1', 'partid' => '2', 'size_id' => '3', 'duration' => '00:15:00', 'created_at' => '2016-03-27 00:00:00', 'updated_at' => '2016-03-27 00:00:00'));
        \DB::table('quote_hours')->insert(array('part_category_id' => '1', 'partid' => '3', 'size_id' => '1', 'duration' => '00:15:00', 'created_at' => '2016-03-27 00:00:00', 'updated_at' => '2016-03-27 00:00:00'));
        \DB::table('quote_hours')->insert(array('part_category_id' => '1', 'partid' => '3', 'size_id' => '2', 'duration' => '00:15:00', 'created_at' => '2016-03-27 00:00:00', 'updated_at' => '2016-03-27 00:00:00'));
        \DB::table('quote_hours')->insert(array('part_category_id' => '1', 'partid' => '3', 'size_id' => '3', 'duration' => '00:15:00', 'created_at' => '2016-03-27 00:00:00', 'updated_at' => '2016-03-27 00:00:00'));
        \DB::table('quote_hours')->insert(array('part_category_id' => '1', 'partid' => '4', 'size_id' => '1', 'duration' => '00:15:00', 'created_at' => '2016-03-27 00:00:00', 'updated_at' => '2016-03-27 00:00:00'));
        \DB::table('quote_hours')->insert(array('part_category_id' => '1', 'partid' => '4', 'size_id' => '2', 'duration' => '00:15:00', 'created_at' => '2016-03-27 00:00:00', 'updated_at' => '2016-03-27 00:00:00'));
        \DB::table('quote_hours')->insert(array('part_category_id' => '1', 'partid' => '4', 'size_id' => '3', 'duration' => '00:15:00', 'created_at' => '2016-03-27 00:00:00', 'updated_at' => '2016-03-27 00:00:00'));
        \DB::table('quote_hours')->insert(array('part_category_id' => '2', 'partid' => '1', 'size_id' => '1', 'duration' => '00:15:00', 'created_at' => '2016-03-27 00:00:00', 'updated_at' => '2016-03-27 00:00:00'));
        \DB::table('quote_hours')->insert(array('part_category_id' => '2', 'partid' => '1', 'size_id' => '2', 'duration' => '00:15:00', 'created_at' => '2016-03-27 00:00:00', 'updated_at' => '2016-03-27 00:00:00'));
        \DB::table('quote_hours')->insert(array('part_category_id' => '2', 'partid' => '1', 'size_id' => '3', 'duration' => '00:15:00', 'created_at' => '2016-03-27 00:00:00', 'updated_at' => '2016-03-27 00:00:00'));
        \DB::table('quote_hours')->insert(array('part_category_id' => '2', 'partid' => '2', 'size_id' => '1', 'duration' => '00:15:00', 'created_at' => '2016-03-27 00:00:00', 'updated_at' => '2016-03-27 00:00:00'));
        \DB::table('quote_hours')->insert(array('part_category_id' => '2', 'partid' => '2', 'size_id' => '2', 'duration' => '00:15:00', 'created_at' => '2016-03-27 00:00:00', 'updated_at' => '2016-03-27 00:00:00'));
        \DB::table('quote_hours')->insert(array('part_category_id' => '2', 'partid' => '2', 'size_id' => '3', 'duration' => '00:15:00', 'created_at' => '2016-03-27 00:00:00', 'updated_at' => '2016-03-27 00:00:00'));
        \DB::table('quote_hours')->insert(array('part_category_id' => '2', 'partid' => '3', 'size_id' => '1', 'duration' => '00:15:00', 'created_at' => '2016-03-27 00:00:00', 'updated_at' => '2016-03-27 00:00:00'));
        \DB::table('quote_hours')->insert(array('part_category_id' => '2', 'partid' => '3', 'size_id' => '2', 'duration' => '00:15:00', 'created_at' => '2016-03-27 00:00:00', 'updated_at' => '2016-03-27 00:00:00'));
        \DB::table('quote_hours')->insert(array('part_category_id' => '2', 'partid' => '3', 'size_id' => '3', 'duration' => '00:15:00', 'created_at' => '2016-03-27 00:00:00', 'updated_at' => '2016-03-27 00:00:00'));
        \DB::table('quote_hours')->insert(array('part_category_id' => '2', 'partid' => '4', 'size_id' => '1', 'duration' => '00:15:00', 'created_at' => '2016-03-27 00:00:00', 'updated_at' => '2016-03-27 00:00:00'));
        \DB::table('quote_hours')->insert(array('part_category_id' => '2', 'partid' => '4', 'size_id' => '2', 'duration' => '00:15:00', 'created_at' => '2016-03-27 00:00:00', 'updated_at' => '2016-03-27 00:00:00'));
        \DB::table('quote_hours')->insert(array('part_category_id' => '2', 'partid' => '4', 'size_id' => '3', 'duration' => '00:15:00', 'created_at' => '2016-03-27 00:00:00', 'updated_at' => '2016-03-27 00:00:00'));
        \DB::table('quote_hours')->insert(array('part_category_id' => '2', 'partid' => '5', 'size_id' => '1', 'duration' => '00:15:00', 'created_at' => '2016-03-27 00:00:00', 'updated_at' => '2016-03-27 00:00:00'));
        \DB::table('quote_hours')->insert(array('part_category_id' => '2', 'partid' => '5', 'size_id' => '2', 'duration' => '00:15:00', 'created_at' => '2016-03-27 00:00:00', 'updated_at' => '2016-03-27 00:00:00'));
        \DB::table('quote_hours')->insert(array('part_category_id' => '2', 'partid' => '5', 'size_id' => '3', 'duration' => '00:15:00', 'created_at' => '2016-03-27 00:00:00', 'updated_at' => '2016-03-27 00:00:00'));
        \DB::table('quote_hours')->insert(array('part_category_id' => '3', 'partid' => '1', 'size_id' => '1', 'duration' => '00:15:00', 'created_at' => '2016-03-27 00:00:00', 'updated_at' => '2016-03-27 00:00:00'));
        \DB::table('quote_hours')->insert(array('part_category_id' => '3', 'partid' => '1', 'size_id' => '2', 'duration' => '00:15:00', 'created_at' => '2016-03-27 00:00:00', 'updated_at' => '2016-03-27 00:00:00'));
        \DB::table('quote_hours')->insert(array('part_category_id' => '3', 'partid' => '1', 'size_id' => '3', 'duration' => '00:15:00', 'created_at' => '2016-03-27 00:00:00', 'updated_at' => '2016-03-27 00:00:00'));
        \DB::table('quote_hours')->insert(array('part_category_id' => '3', 'partid' => '2', 'size_id' => '1', 'duration' => '00:15:00', 'created_at' => '2016-03-27 00:00:00', 'updated_at' => '2016-03-27 00:00:00'));
        \DB::table('quote_hours')->insert(array('part_category_id' => '3', 'partid' => '2', 'size_id' => '2', 'duration' => '00:15:00', 'created_at' => '2016-03-27 00:00:00', 'updated_at' => '2016-03-27 00:00:00'));
        \DB::table('quote_hours')->insert(array('part_category_id' => '3', 'partid' => '2', 'size_id' => '3', 'duration' => '00:15:00', 'created_at' => '2016-03-27 00:00:00', 'updated_at' => '2016-03-27 00:00:00'));
        \DB::table('quote_hours')->insert(array('part_category_id' => '3', 'partid' => '3', 'size_id' => '1', 'duration' => '00:15:00', 'created_at' => '2016-03-27 00:00:00', 'updated_at' => '2016-03-27 00:00:00'));
        \DB::table('quote_hours')->insert(array('part_category_id' => '3', 'partid' => '3', 'size_id' => '2', 'duration' => '00:15:00', 'created_at' => '2016-03-27 00:00:00', 'updated_at' => '2016-03-27 00:00:00'));
        \DB::table('quote_hours')->insert(array('part_category_id' => '3', 'partid' => '3', 'size_id' => '3', 'duration' => '00:15:00', 'created_at' => '2016-03-27 00:00:00', 'updated_at' => '2016-03-27 00:00:00'));
        \DB::table('quote_hours')->insert(array('part_category_id' => '3', 'partid' => '4', 'size_id' => '1', 'duration' => '00:15:00', 'created_at' => '2016-03-27 00:00:00', 'updated_at' => '2016-03-27 00:00:00'));
        \DB::table('quote_hours')->insert(array('part_category_id' => '3', 'partid' => '4', 'size_id' => '2', 'duration' => '00:15:00', 'created_at' => '2016-03-27 00:00:00', 'updated_at' => '2016-03-27 00:00:00'));
        \DB::table('quote_hours')->insert(array('part_category_id' => '3', 'partid' => '4', 'size_id' => '3', 'duration' => '00:15:00', 'created_at' => '2016-03-27 00:00:00', 'updated_at' => '2016-03-27 00:00:00'));
        \DB::table('quote_hours')->insert(array('part_category_id' => '4', 'partid' => '1', 'size_id' => '1', 'duration' => '00:15:00', 'created_at' => '2016-03-27 00:00:00', 'updated_at' => '2016-03-27 00:00:00'));
        \DB::table('quote_hours')->insert(array('part_category_id' => '4', 'partid' => '1', 'size_id' => '2', 'duration' => '00:15:00', 'created_at' => '2016-03-27 00:00:00', 'updated_at' => '2016-03-27 00:00:00'));
        \DB::table('quote_hours')->insert(array('part_category_id' => '4', 'partid' => '1', 'size_id' => '3', 'duration' => '00:15:00', 'created_at' => '2016-03-27 00:00:00', 'updated_at' => '2016-03-27 00:00:00'));
        \DB::table('quote_hours')->insert(array('part_category_id' => '4', 'partid' => '2', 'size_id' => '1', 'duration' => '00:15:00', 'created_at' => '2016-03-27 00:00:00', 'updated_at' => '2016-03-27 00:00:00'));
        \DB::table('quote_hours')->insert(array('part_category_id' => '4', 'partid' => '2', 'size_id' => '2', 'duration' => '00:15:00', 'created_at' => '2016-03-27 00:00:00', 'updated_at' => '2016-03-27 00:00:00'));
        \DB::table('quote_hours')->insert(array('part_category_id' => '4', 'partid' => '2', 'size_id' => '3', 'duration' => '00:15:00', 'created_at' => '2016-03-27 00:00:00', 'updated_at' => '2016-03-27 00:00:00'));
        \DB::table('quote_hours')->insert(array('part_category_id' => '4', 'partid' => '3', 'size_id' => '1', 'duration' => '00:15:00', 'created_at' => '2016-03-27 00:00:00', 'updated_at' => '2016-03-27 00:00:00'));
        \DB::table('quote_hours')->insert(array('part_category_id' => '4', 'partid' => '3', 'size_id' => '2', 'duration' => '00:15:00', 'created_at' => '2016-03-27 00:00:00', 'updated_at' => '2016-03-27 00:00:00'));
        \DB::table('quote_hours')->insert(array('part_category_id' => '4', 'partid' => '3', 'size_id' => '3', 'duration' => '00:15:00', 'created_at' => '2016-03-27 00:00:00', 'updated_at' => '2016-03-27 00:00:00'));
        \DB::table('quote_hours')->insert(array('part_category_id' => '4', 'partid' => '4', 'size_id' => '1', 'duration' => '00:15:00', 'created_at' => '2016-03-27 00:00:00', 'updated_at' => '2016-03-27 00:00:00'));
        \DB::table('quote_hours')->insert(array('part_category_id' => '4', 'partid' => '4', 'size_id' => '2', 'duration' => '00:15:00', 'created_at' => '2016-03-27 00:00:00', 'updated_at' => '2016-03-27 00:00:00'));
        \DB::table('quote_hours')->insert(array('part_category_id' => '4', 'partid' => '4', 'size_id' => '3', 'duration' => '00:15:00', 'created_at' => '2016-03-27 00:00:00', 'updated_at' => '2016-03-27 00:00:00'));
        \DB::table('quote_hours')->insert(array('part_category_id' => '4', 'partid' => '5', 'size_id' => '1', 'duration' => '00:15:00', 'created_at' => '2016-03-27 00:00:00', 'updated_at' => '2016-03-27 00:00:00'));
        \DB::table('quote_hours')->insert(array('part_category_id' => '4', 'partid' => '5', 'size_id' => '2', 'duration' => '00:15:00', 'created_at' => '2016-03-27 00:00:00', 'updated_at' => '2016-03-27 00:00:00'));
        \DB::table('quote_hours')->insert(array('part_category_id' => '4', 'partid' => '5', 'size_id' => '3', 'duration' => '00:15:00', 'created_at' => '2016-03-27 00:00:00', 'updated_at' => '2016-03-27 00:00:00'));
        \DB::table('quote_hours')->insert(array('part_category_id' => '4', 'partid' => '6', 'size_id' => '1', 'duration' => '00:15:00', 'created_at' => '2016-03-27 00:00:00', 'updated_at' => '2016-03-27 00:00:00'));
        \DB::table('quote_hours')->insert(array('part_category_id' => '4', 'partid' => '6', 'size_id' => '2', 'duration' => '00:15:00', 'created_at' => '2016-03-27 00:00:00', 'updated_at' => '2016-03-27 00:00:00'));
        \DB::table('quote_hours')->insert(array('part_category_id' => '4', 'partid' => '6', 'size_id' => '3', 'duration' => '00:15:00', 'created_at' => '2016-03-27 00:00:00', 'updated_at' => '2016-03-27 00:00:00'));
        \DB::table('quote_hours')->insert(array('part_category_id' => '4', 'partid' => '7', 'size_id' => '1', 'duration' => '00:15:00', 'created_at' => '2016-03-27 00:00:00', 'updated_at' => '2016-03-27 00:00:00'));
        \DB::table('quote_hours')->insert(array('part_category_id' => '4', 'partid' => '7', 'size_id' => '2', 'duration' => '00:15:00', 'created_at' => '2016-03-27 00:00:00', 'updated_at' => '2016-03-27 00:00:00'));
        \DB::table('quote_hours')->insert(array('part_category_id' => '4', 'partid' => '7', 'size_id' => '3', 'duration' => '00:15:00', 'created_at' => '2016-03-27 00:00:00', 'updated_at' => '2016-03-27 00:00:00'));
        \DB::table('quote_hours')->insert(array('part_category_id' => '4', 'partid' => '8', 'size_id' => '1', 'duration' => '00:15:00', 'created_at' => '2016-03-27 00:00:00', 'updated_at' => '2016-03-27 00:00:00'));
        \DB::table('quote_hours')->insert(array('part_category_id' => '4', 'partid' => '8', 'size_id' => '2', 'duration' => '00:15:00', 'created_at' => '2016-03-27 00:00:00', 'updated_at' => '2016-03-27 00:00:00'));
        \DB::table('quote_hours')->insert(array('part_category_id' => '4', 'partid' => '8', 'size_id' => '3', 'duration' => '00:15:00', 'created_at' => '2016-03-27 00:00:00', 'updated_at' => '2016-03-27 00:00:00'));
        \DB::table('quote_hours')->insert(array('part_category_id' => '5', 'partid' => '1', 'size_id' => '1', 'duration' => '00:15:00', 'created_at' => '2016-03-27 00:00:00', 'updated_at' => '2016-03-27 00:00:00'));
        \DB::table('quote_hours')->insert(array('part_category_id' => '5', 'partid' => '1', 'size_id' => '2', 'duration' => '00:15:00', 'created_at' => '2016-03-27 00:00:00', 'updated_at' => '2016-03-27 00:00:00'));
        \DB::table('quote_hours')->insert(array('part_category_id' => '5', 'partid' => '1', 'size_id' => '3', 'duration' => '00:15:00', 'created_at' => '2016-03-27 00:00:00', 'updated_at' => '2016-03-27 00:00:00'));
        \DB::table('quote_hours')->insert(array('part_category_id' => '5', 'partid' => '2', 'size_id' => '1', 'duration' => '00:15:00', 'created_at' => '2016-03-27 00:00:00', 'updated_at' => '2016-03-27 00:00:00'));
        \DB::table('quote_hours')->insert(array('part_category_id' => '5', 'partid' => '2', 'size_id' => '2', 'duration' => '00:15:00', 'created_at' => '2016-03-27 00:00:00', 'updated_at' => '2016-03-27 00:00:00'));
        \DB::table('quote_hours')->insert(array('part_category_id' => '5', 'partid' => '2', 'size_id' => '3', 'duration' => '00:15:00', 'created_at' => '2016-03-27 00:00:00', 'updated_at' => '2016-03-27 00:00:00'));
        \DB::table('quote_hours')->insert(array('part_category_id' => '6', 'partid' => '1', 'size_id' => '1', 'duration' => '00:15:00', 'created_at' => '2016-03-27 00:00:00', 'updated_at' => '2016-03-27 00:00:00'));
        \DB::table('quote_hours')->insert(array('part_category_id' => '6', 'partid' => '1', 'size_id' => '2', 'duration' => '00:15:00', 'created_at' => '2016-03-27 00:00:00', 'updated_at' => '2016-03-27 00:00:00'));
        \DB::table('quote_hours')->insert(array('part_category_id' => '6', 'partid' => '1', 'size_id' => '3', 'duration' => '00:15:00', 'created_at' => '2016-03-27 00:00:00', 'updated_at' => '2016-03-27 00:00:00'));
        \DB::table('quote_hours')->insert(array('part_category_id' => '6', 'partid' => '2', 'size_id' => '1', 'duration' => '00:15:00', 'created_at' => '2016-03-27 00:00:00', 'updated_at' => '2016-03-27 00:00:00'));
        \DB::table('quote_hours')->insert(array('part_category_id' => '6', 'partid' => '2', 'size_id' => '2', 'duration' => '00:15:00', 'created_at' => '2016-03-27 00:00:00', 'updated_at' => '2016-03-27 00:00:00'));
        \DB::table('quote_hours')->insert(array('part_category_id' => '6', 'partid' => '2', 'size_id' => '3', 'duration' => '00:15:00', 'created_at' => '2016-03-27 00:00:00', 'updated_at' => '2016-03-27 00:00:00'));
        \DB::table('quote_hours')->insert(array('part_category_id' => '6', 'partid' => '3', 'size_id' => '1', 'duration' => '00:15:00', 'created_at' => '2016-03-27 00:00:00', 'updated_at' => '2016-03-27 00:00:00'));
        \DB::table('quote_hours')->insert(array('part_category_id' => '6', 'partid' => '3', 'size_id' => '2', 'duration' => '00:15:00', 'created_at' => '2016-03-27 00:00:00', 'updated_at' => '2016-03-27 00:00:00'));
        \DB::table('quote_hours')->insert(array('part_category_id' => '6', 'partid' => '3', 'size_id' => '3', 'duration' => '00:15:00', 'created_at' => '2016-03-27 00:00:00', 'updated_at' => '2016-03-27 00:00:00'));

        // Table roles
        \DB::table('roles')->insert(array('name' => 'SUPER ADMIN'));
        \DB::table('roles')->insert(array('name' => 'ADMINISTRATOR'));
        \DB::table('roles')->insert(array('name' => 'LEADER'));
        \DB::table('roles')->insert(array('name' => 'CLEANER'));
        
        // Table sizes
        \DB::table('sizes')->insert(array('name' => 'SMALL'));
        \DB::table('sizes')->insert(array('name' => 'MEDIUM'));
        \DB::table('sizes')->insert(array('name' => 'LARGE'));

        // Table states
        \DB::table('states')->insert(array('name' => 'NEW SOUTH WALES'));
        \DB::table('states')->insert(array('name' => 'NORTHERN TERRITORY'));
        \DB::table('states')->insert(array('name' => 'QUEENSLAND'));
        \DB::table('states')->insert(array('name' => 'TASMANIA'));
        \DB::table('states')->insert(array('name' => 'SOUTH AUSTRALIA'));
        \DB::table('states')->insert(array('name' => 'VICTORIA'));
        \DB::table('states')->insert(array('name' => 'WESTERN AUSTRALIA'));

        // Table status_jobs
        \DB::table('status_jobs')->insert(array('name' => 'UNASSIGNED'));
        \DB::table('status_jobs')->insert(array('name' => 'ASSIGNED'));
        \DB::table('status_jobs')->insert(array('name' => 'ACCEPTED'));
        \DB::table('status_jobs')->insert(array('name' => 'REJECTED'));
        \DB::table('status_jobs')->insert(array('name' => 'COMPLETED'));
        \DB::table('status_jobs')->insert(array('name' => 'POSTPONED'));
        \DB::table('status_jobs')->insert(array('name' => 'CANCELED'));

        // Table street_types
        \DB::table('street_types')->insert(array('name' => 'STREET'));
        \DB::table('street_types')->insert(array('name' => 'ROAD'));
        \DB::table('street_types')->insert(array('name' => 'DRIVE'));
        \DB::table('street_types')->insert(array('name' => 'PARADE'));
        \DB::table('street_types')->insert(array('name' => 'PLACE'));
        \DB::table('street_types')->insert(array('name' => 'LANE'));
        \DB::table('street_types')->insert(array('name' => 'CLOSE'));
        \DB::table('street_types')->insert(array('name' => 'COURT'));
        \DB::table('street_types')->insert(array('name' => 'CRESCENT'));
        \DB::table('street_types')->insert(array('name' => 'ACCESS'));
        \DB::table('street_types')->insert(array('name' => 'ALLEY'));
        \DB::table('street_types')->insert(array('name' => 'APPROACH'));
        \DB::table('street_types')->insert(array('name' => 'ARCADE'));
        \DB::table('street_types')->insert(array('name' => 'AVENUE'));
        \DB::table('street_types')->insert(array('name' => 'BOULEVARD'));
        \DB::table('street_types')->insert(array('name' => 'BROW'));
        \DB::table('street_types')->insert(array('name' => 'BYPASS'));
        \DB::table('street_types')->insert(array('name' => 'CIRCUIT'));
        \DB::table('street_types')->insert(array('name' => 'CENTRE'));
        \DB::table('street_types')->insert(array('name' => 'CHASE'));
        \DB::table('street_types')->insert(array('name' => 'CIRCUS'));
        \DB::table('street_types')->insert(array('name' => 'CORNER'));
        \DB::table('street_types')->insert(array('name' => 'CONCOURSE'));
        \DB::table('street_types')->insert(array('name' => 'COVE'));
        \DB::table('street_types')->insert(array('name' => 'COPSE'));
        \DB::table('street_types')->insert(array('name' => 'CROSSING'));
        \DB::table('street_types')->insert(array('name' => 'CUL-DE-SAC'));
        \DB::table('street_types')->insert(array('name' => 'CAUSEWAY'));
        \DB::table('street_types')->insert(array('name' => 'END'));
        \DB::table('street_types')->insert(array('name' => 'ESPLANADE'));
        \DB::table('street_types')->insert(array('name' => 'FLAT'));
        \DB::table('street_types')->insert(array('name' => 'FRONTAGE'));
        \DB::table('street_types')->insert(array('name' => 'FREEWAY'));
        \DB::table('street_types')->insert(array('name' => 'GARDENS'));
        \DB::table('street_types')->insert(array('name' => 'GLADE'));
        \DB::table('street_types')->insert(array('name' => 'GLEN'));
        \DB::table('street_types')->insert(array('name' => 'GROVE'));
        \DB::table('street_types')->insert(array('name' => 'GREEN'));
        \DB::table('street_types')->insert(array('name' => 'HEIGHTS'));
        \DB::table('street_types')->insert(array('name' => 'HIGHWAY'));
        \DB::table('street_types')->insert(array('name' => 'JUNCTION'));
        \DB::table('street_types')->insert(array('name' => 'LINK'));
        \DB::table('street_types')->insert(array('name' => 'LOOP'));
        \DB::table('street_types')->insert(array('name' => 'MAIL'));
        \DB::table('street_types')->insert(array('name' => 'MEWS'));
        \DB::table('street_types')->insert(array('name' => 'PARK'));
        \DB::table('street_types')->insert(array('name' => 'PACKET'));
        \DB::table('street_types')->insert(array('name' => 'PARKWAY'));
        \DB::table('street_types')->insert(array('name' => 'POINT'));
        \DB::table('street_types')->insert(array('name' => 'PROMENADE'));
        \DB::table('street_types')->insert(array('name' => 'QUAY'));
        \DB::table('street_types')->insert(array('name' => 'RIDGE'));
        \DB::table('street_types')->insert(array('name' => 'RESERVE'));
        \DB::table('street_types')->insert(array('name' => 'RIDGEWAY'));
        \DB::table('street_types')->insert(array('name' => 'RISE'));
        \DB::table('street_types')->insert(array('name' => 'ROADS'));
        \DB::table('street_types')->insert(array('name' => 'ROW'));
        \DB::table('street_types')->insert(array('name' => 'SQUARE'));
        \DB::table('street_types')->insert(array('name' => 'STRIP'));
        \DB::table('street_types')->insert(array('name' => 'TAM'));
        \DB::table('street_types')->insert(array('name' => 'TERRACE'));
        \DB::table('street_types')->insert(array('name' => 'THOROUGHFARE'));
        \DB::table('street_types')->insert(array('name' => 'TRACK'));
        \DB::table('street_types')->insert(array('name' => 'TRUNK-WAY'));
        \DB::table('street_types')->insert(array('name' => 'VIEW'));
        \DB::table('street_types')->insert(array('name' => 'VISTA'));
        \DB::table('street_types')->insert(array('name' => 'WALK'));
        \DB::table('street_types')->insert(array('name' => 'WAY'));
        \DB::table('street_types')->insert(array('name' => 'WALKWAY'));
        \DB::table('street_types')->insert(array('name' => 'YARD'));
    }
}